spring:
  application:
    name: aws-infra-studying

  datasource:
    url: jdbc:h2:tcp://localhost/~/testtest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
